#!/system/bin/sh
# 
# Mounts Ext Drive / Checks Data Directories
# WesGarner for OpenEclair

echo "--- Mounting Ext Drive / Checking Data Directories";
if [ -e /dev/block/mmcblk0p2 ];
then
	# fsck the sdcard filesystem first
	e2fsck -y /dev/block/mmcblk0p2;

	# set property with exit code in case an error occurs
	setprop cm.e2fsck.errors $?;
	
	# mount and set perms
	busybox mount -o noatime,nodiratime -t auto /dev/block/mmcblk0p2 /system/sd;
	busybox chown 1000:1000 /system/sd;
	busybox chmod 771 /system/sd;
fi;

# clean up any old symlinks, create directories
for i in app app-private;
    do
	if [ -h /data/$i ];
	then
		rm /data/$i;
	fi;
	if [ ! -d /data/$i ];
	then
		mkdir /data/$i;
		busybox chown 1000:1000 /data/$i;
		busybox chmod 771 /data/$i;
	fi;
done;
